# Generated by Django 4.2.26 on 2025-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('oz', 'oz'), ('ml', 'ml'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('barspoon', 'barspoon'), ('dash', 'dash')], max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional URL to the recipe source', null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('oz', 'oz'), ('ml', 'ml'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('barspoon', 'barspoon'), ('dash', 'dash'), ('drops', 'drops')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('oz', 'oz'), ('ml', 'ml'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('barspoon', 'barspoon'), ('dash', 'dash'), ('drops', 'drops'), ('spritz', 'spritz'), ('rinse', 'rinse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('oz', 'oz'), ('ml', 'ml'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('barspoon', 'barspoon'), ('dash', 'dash'), ('drops', 'drops'), ('spritz', 'spritz'), ('rinse', 'rinse'), ('pinch', 'pinch')], max_length=20),
        ),
    ]
