# Generated by Django 4.2.26 on 2025-12-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_add_units_and_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this category')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_generic',
            field=models.BooleanField(default=False, help_text='True if this is the auto-created generic ingredient for a category'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category this ingredient belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.ingredientcategory'),
        ),
    ]
