# Generated by Django 4.2.26 on 2026-05-06 05:37

from django.db import migrations


def set_stock_75(apps, schema_editor):
    Ingredient = apps.get_model('cocktails', 'Ingredient')
    Ingredient.objects.all().update(stock_level=75)


def revert_stock(apps, schema_editor):
    Ingredient = apps.get_model('cocktails', 'Ingredient')
    Ingredient.objects.all().update(stock_level=100)


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_add_stock_level_menus_buylist'),
    ]

    operations = [
        migrations.RunPython(set_stock_75, revert_stock),
    ]
