# Generated by Django 4.2.26 on 2026-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_set_existing_ingredients_stock_75'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='glass',
            field=models.CharField(blank=True, choices=[('rocks', 'Rocks'), ('old_fashioned', 'Old Fashioned'), ('martini', 'Martini'), ('coupe', 'Coupe'), ('champagne_flute', 'Champagne Flute'), ('collins', 'Collins'), ('shot', 'Shot'), ('glencairn', 'Glencairn')], max_length=20),
        ),
    ]
