# Generated by Django 4.2.26 on 2026-05-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_recipe_description_recipe_glass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cocktails.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cocktails.recipe')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
