# Generated by Django 4.2.26 on 2026-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='bottom_decoration',
            field=models.CharField(choices=[('none', 'None'), ('ume', 'Ume Blossom Branch'), ('taco', 'Taco'), ('maple', 'Maple Branch'), ('acorn', 'Acorns & Oak'), ('pumpkin', 'Pumpkins'), ('wheat', 'Wheat & Dried Grass')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='menu',
            name='top_decoration',
            field=models.CharField(choices=[('none', 'None'), ('ume', 'Ume Blossom Branch'), ('taco', 'Taco'), ('maple', 'Maple Branch'), ('acorn', 'Acorns & Oak'), ('pumpkin', 'Pumpkins'), ('wheat', 'Wheat & Dried Grass')], default='none', max_length=32),
        ),
    ]
